trigger:
  branches:
    include:
      - main

pool:
  vmImage: "windows-latest" # potrzebne dla MSBuild

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  azureSubscription: "GameBackendServiceConnection"
  artifactName: "drop"
  terraformWorkingDir: "Terraform"
  packagePath: "$(System.ArtifactsDirectory)/$(artifactName)/**/*.zip"

stages:
  # ===================================
  # 1️⃣ BUILD & TEST .NET APLIKACJI
  # ===================================
  - stage: Build
    displayName: "Build and Test Application"
    jobs:
      - job: BuildApp
        displayName: "Build .NET App"
        steps:
          - task: NuGetToolInstaller@1

          - task: NuGetCommand@2
            inputs:
              restoreSolution: $(solution)

          - task: VSBuild@1
            inputs:
              solution: $(solution)
              msbuildArgs: >
                /p:DeployOnBuild=true
                /p:WebPublishMethod=Package
                /p:PackageAsSingleFile=true
                /p:SkipInvalidConfigurations=true
                /p:PackageLocation="$(build.artifactStagingDirectory)"
              platform: $(buildPlatform)
              configuration: $(buildConfiguration)

          - task: VSTest@2
            inputs:
              platform: $(buildPlatform)
              configuration: $(buildConfiguration)

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: $(build.artifactStagingDirectory)
              ArtifactName: $(artifactName)

  # ===================================
  # 2️⃣ PROVISION INFRA Z TERRAFORM
  # ===================================
  - stage: Infrastructure
    displayName: "Provision Infrastructure with Terraform"
    dependsOn: Build
    jobs:
      - job: TerraformApply
        displayName: "Terraform Apply"
        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "latest"

          - task: AzureCLI@2
            displayName: "Terraform Init & Apply"
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              workingDirectory: $(terraformWorkingDir)
              inlineScript: |
                Write-Host "Initializing Terraform..."
                terraform init

                Write-Host "Planning Terraform..."
                terraform plan -out=tfplan

                Write-Host "Applying Terraform..."
                terraform apply -auto-approve tfplan

                Write-Host "Fetching Terraform outputs..."
                $appServiceName = terraform output -raw app_service_name
                $resourceGroupName = terraform output -raw resource_group_name

                Write-Host "##vso[task.setvariable variable=AppServiceName;isOutput=true]$appServiceName"
                Write-Host "##vso[task.setvariable variable=ResourceGroupName;isOutput=true]$resourceGroupName"

                Write-Host "App Service Name: $appServiceName"
                Write-Host "Resource Group: $resourceGroupName"

  # ===================================
  # 3️⃣ DEPLOY DO AZURE APP SERVICE
  # ===================================
  - stage: Deploy
    displayName: "Deploy Application to Azure App Service"
    dependsOn: Infrastructure
    jobs:
      - job: DeployWebApp
        displayName: "Deploy Web App"
        variables:
          appServiceName: $[ stageDependencies.Infrastructure.TerraformApply.outputs['AppServiceName'] ]
          resourceGroupName: $[ stageDependencies.Infrastructure.TerraformApply.outputs['ResourceGroupName'] ]
        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: current
              downloadType: single
              artifactName: $(artifactName)
              downloadPath: $(System.ArtifactsDirectory)

          - task: AzureWebApp@1
            displayName: "Deploy App to Azure App Service"
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appServiceName)
              package: $(packagePath)

          - task: AzureCLI@2
            displayName: "Verify Deployment"
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                Write-Host "Verifying deployment..."
                $appUrl = az webapp show --name $(appServiceName) --resource-group $(resourceGroupName) --query defaultHostName --output tsv
                Write-Host "Application URL: https://$appUrl"
